/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluationWorkRouteImport } from './routes/evaluation-work'
import { Route as FailureLibraryRouteImport } from './routes/failure-library'
import { Route as MethodologyRouteImport } from './routes/methodology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationWorkRoute = EvaluationWorkRouteImport.update({
  id: '/evaluation-work',
  path: '/evaluation-work',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureLibraryRoute = FailureLibraryRouteImport.update({
  id: '/failure-library',
  path: '/failure-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation-work': typeof EvaluationWorkRoute
  '/failure-library': typeof FailureLibraryRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation-work': typeof EvaluationWorkRoute
  '/failure-library': typeof FailureLibraryRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluation-work': typeof EvaluationWorkRoute
  '/failure-library': typeof FailureLibraryRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluation-work' | '/failure-library' | '/methodology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evaluation-work' | '/failure-library' | '/methodology'
  id:
    '__root__' | '/' | '/evaluation-work' | '/failure-library' | '/methodology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationWorkRoute: typeof EvaluationWorkRoute
  FailureLibraryRoute: typeof FailureLibraryRoute
  MethodologyRoute: typeof MethodologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-work': {
      id: '/evaluation-work'
      path: '/evaluation-work'
      fullPath: '/evaluation-work'
      preLoaderRoute: typeof EvaluationWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure-library': {
      id: '/failure-library'
      path: '/failure-library'
      fullPath: '/failure-library'
      preLoaderRoute: typeof FailureLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationWorkRoute: EvaluationWorkRoute,
  FailureLibraryRoute: FailureLibraryRoute,
  MethodologyRoute: MethodologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
